### PR TITLE
add VMT7 RGT7 CGU7 Target for bf4.5 at32 test 

### PR DESCRIPTION
**Pull request by shanggl**
this pr is prepare  for test bf 4.5 at32 support 

add GREATMOUNTAINRCF435 target :AT32F435VMT7 based open source hardware target 
add NEUTRONRCF435MINI  target : AT32F435CGU7 based  25.5*25.5 aio fc target
modify NEUTRONRCF435 target to NEUTRONRCF435SE  AT32F435RGT7 based 30*30 fc target

### CODE REVIEW

**Review by haslinghuis — CHANGES_REQUESTED** [review]
@shanggl PR needs to be a feature branch instead of master branch.

USE_UARTx _ and SERIAL_PORT_COUNT settings should be defined in firmware

**Comment by nerdCopter** [comment]
image

Create new branch from `master`. Modify the branch. Pull-request the branch.

**Comment by shanggl** [comment]
i will make a new branch

**Comment by shanggl** [comment]
> @shanggl PR needs to be a feature branch instead of master branch.
> 
> USE_UARTx _ and SERIAL_PORT_COUNT settings should be defined in firmware

there is a problem  eg. 
NEUTRONRCF435MINI use usart 1 2 3 5 7 
NEUTRONRCF435SE use  usart  1 2 3 4 5 

this is target specified , how to config it in the AT32F435 firmware ?

**Comment by haslinghuis** [comment]
1. #define UART1 - UART7 in target.h
2. Only assign a PIN when applicable.
3. SERIAL_PORT_COUNT will be 7 + 1 :thinking:

**Pull request closed without merging**
