### PR TITLE
Fix custom alignment

### PR DESCRIPTION
**Pull request by haslinghuis**
See comment https://github.com/betaflight/config/pull/645#issuecomment-2556927473

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Comment by ledvinap** [comment]
Why? Valid value is -3600..3600.

**Comment by haslinghuis** [comment]
@ledvinap

IMHO if signed it should be -1800..1800 and why use decidegrees. Only clockwise may be easier but just a preference.
Should I change to `-450` instead ?

**Comment by ledvinap** [comment]
I'd keep current state for now, but this PR won't hurt ...

**Review by ledvinap — APPROVED** [review]
Decide yourself ..

**Pull request merged**
