### PR TITLE
[target] TALONF7V2 add ACC/GYRO SPI ICM20602

### PR DESCRIPTION
**Pull request by nerdCopter**
- https://discord.com/channels/868013470023548938/1293648238838157406/1293656240072687657

### CODE REVIEW

**Comment by haslinghuis** [comment]
https://www.getfpv.com/heli-nation-talon-f7-v2-20x20-flight-controller.html

**Comment by nerdCopter** [comment]
seems V1 had ICM20602, but there is no `TALONF7` in configs repo.
https://www.myfpvstore.com/fpv-electronics/flight-controllers/talon-flight-controller/

**Comment by haslinghuis** [comment]
That one uses CLRACINGF7 target.

**Comment by nerdCopter** [comment]
closing, does not seem accurate. pilot's board matches V1 layout even though screen-printed with V2.

**Pull request closed without merging**
