### PR TITLE
Add GREATMOUNTAINF435MINI

### PR DESCRIPTION
**Pull request by ASDosjani**
20x20 FC with AT32F435CGU7 MCU, DPS310 baro, ICM42688 gyro, 128MB flash.
IMG_20240602_135851
IMG_20240602_135814

### CODE REVIEW

**Comment by ASDosjani** [comment]
@haslinghuis can you check it out?

**Comment by nerdCopter** [comment]
@ASDosjani  same request as https://github.com/betaflight/config/pull/443#issuecomment-2188952467

**Comment by ASDosjani** [comment]
@nerdCopter @haslinghuis @sugaarK will this be merged with CCRCF435FC?

**Comment by haslinghuis** [comment]
Closing as design does not comply with the target submission policy: https://betaflight.com/docs/development/manufacturer/requirements-for-submission-of-targets

**Pull request closed without merging**
