### PR TITLE
Added configuration for Diatone Mamba MK5 435AI (AT32 Based)

### PR DESCRIPTION
**Pull request by shaneshort**
Resubmitting from a new branch as requested in #385

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Comment by ot0tot** [comment]
Have you tested whether the current sensor works?

**Review by haslinghuis — CHANGES_REQUESTED** [review]
An official target will come from Diatone.

**Comment by sugaarK** [comment]
we work directly with diatone.. lets see what they say

**Comment by shaneshort** [comment]
I contacted them directly and they supplied the following file, which is what I based my work on. 

I can forward the correspondence if required. 

[MAMBAF435_2023A-08151743.txt](https://github.com/betaflight/config/files/15004164/MAMBAF435_2023A-08151743.txt)

**Comment by shaneshort** [comment]
> Have you tested whether the current sensor works?
I have not personally, I can today.
 
> I thought the decision was not to add these targets as Diatone decided to forgo the usual Betaflight approval process.
Whilst I understand you want them to go through the approval process, from a consumer's perspective it makes for a poor experience. For myself and others who have purchased these controllers with no knowledge that they're not officially supported by Betaflight, sucks.

Before doing this target I didn't see any notes that 'unofficial' targets wouldn't be accepted, if there is-- can someone point me in the right direction?

**Comment by freasy** [comment]
@shaneshort we have this board in hand and working on an official target. Please be patient a little longer, you can find the official pr here https://github.com/betaflight/config/pull/391

**Comment by shaneshort** [comment]
> @shaneshort we have this board in hand and working on an official target. Please be patient a little longer, you can find the official pr here #391

I'm a little confused that you couldn't simply validate my work rather than duplicating it on another PR. TBH, This has been a really strange experience-- I guess I'll just close this PR and concentrate my efforts elsewhere.

**Comment by freasy** [comment]
> > @shaneshort we have this board in hand and working on an official target. Please be patient a little longer, you can find the official pr here #391
> 
> I'm a little confused that you couldn't simply validate my work rather than duplicating it on another PR. TBH, This has been a really strange experience-- I guess I'll just close this PR and concentrate my efforts elsewhere.

Your PR came in after we already started working on it. So as we won't throw away any work, we raised our pr, so we have all work visible.

Thank you for your effort, much appreciated! We will use both to form a perfect target 💪

**Pull request closed without merging**
