### PR TITLE
Update DMA stream on SPEEDYBEEF7V3

### PR DESCRIPTION
**Pull request by haslinghuis**
Fixes: https://github.com/betaflight/betaflight/issues/12965

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Comment by Martivip** [comment]
@haslinghuis Hi I've just freshly flashed and applied Custom Defaults and still no DMA after LedStrip ON

**Comment by haslinghuis** [comment]
Custom defaults? The fix has not yet been merged for unified targets. Should work on 4.5.0 preview.

**Comment by Martivip** [comment]
> Custom defaults? The fix has not yet been merged for unified targets. Should work on 4.5.0 preview.

ahhhh I see, Thank You

**Comment by Martivip** [comment]
> Custom defaults? The fix has not yet been merged for unified targets. Should work on 4.5.0 preview.

but this Unified Target will be updated before 4.5 release right, only someone need to approve and merged to unified targets right ?

**Comment by haslinghuis** [comment]
This repo is used for config.h configuration as used from firmware >= 4.5.0.

Unified targets are for previous firmware releases < 4.5.0. It just need one more member approval before I can merge it.

**Comment by Martivip** [comment]
> This repo is used for config.h configuration as used from firmware >= 4.5.0.
> 
> Unified targets are for previous firmware releases < 4.5.0. It just need one more member approval before I can merge it.

Ok Thanks for explanation, simple change but I'm not allowed to approve ...ok lets wait :)

**Pull request merged**
