### PR TITLE
Add target FLYCOLORF7_SE

### PR DESCRIPTION
**Pull request by tobeornottobe81**
add new target , thank you!

### CODE REVIEW

**Comment by tobeornottobe81** [comment]
I just saw this today, https://betaflight.com/docs/development/manufacturer/config-target-guidance,should we follow it now?

**Comment by sugaarK** [comment]
> I just saw this today, https://betaflight.com/docs/development/manufacturer/config-target-guidance should we follow it now?

100%... I have some questions as well about some one calming to represent your company calling him self Richard and using the git account name tmotorsg. he did delete his comments and it looks like his account but the entire conversation was preserved by the git notifications and my email account..  I did get your email. but have been sick the last few days.. maybe we can chat on Facebook or discord and clear up this issues with this guy...

**Comment by tobeornottobe81** [comment]
> > I just saw this today, https://betaflight.com/docs/development/manufacturer/config-target-guidance should we follow it now?
> 
> 100%... I have some questions as well about some one calming to represent your company calling him self Richard and using the git account name tmotorsg. he did delete his comments and it looks like his account but the entire conversation was preserved by the git notifications and my email account.. I did get your email. but have been sick the last few days.. maybe we can chat on Facebook or discord and clear up this issues with this guy...
> 
I'm sorry，I hope you get better soon.
We don't know this person named tmotorsg/Richard, nor is he one of us. We have seen this person arguing and threatening others with people from Tmotor company on BLHELI before.
Yes, we used “support@fyjl.net”  company email has sent you an email, and the copied email addresses in the email are all from Flycolor.
We will chat with you later after downloading and installing Discord. Let's talk about how to become a partner of Betaflight. Or email communication can continue. 
Can we first approve the review of our FLYCOLORF7_SE ,Because we need to upgrade to 4.5 or above online for testing, 
thank you!

**Comment by tobeornottobe81** [comment]
> > I just saw this today, https://betaflight.com/docs/development/manufacturer/config-target-guidance should we follow it now?
> 
> 100%... I have some questions as well about some one calming to represent your company calling him self Richard and using the git account name tmotorsg. he did delete his comments and it looks like his account but the entire conversation was preserved by the git notifications and my email account.. I did get your email. but have been sick the last few days.. maybe we can chat on Facebook or discord and clear up this issues with this guy...
> 
I'm sorry，I hope you get better soon.
We don't know this person named tmotorsg/Richard, nor is he one of us. We have seen this person arguing and threatening others with people from Tmotor company on BLHELI before.
Yes, we used “support@fyjl.net”  company email has sent you an email, and the copied email addresses in the email are all from Flycolor.
We will chat with you later after downloading and installing Discord. Let's talk about how to become a partner of Betaflight. Or email communication can continue. 
Can we first approve the review of our FLYCOLORF7_SE ,Because we need to upgrade to 4.5 or above online for testing, 
thank you!

**Comment by sugaarK** [comment]
@haslinghuis @ot0tot  did we get this one sorted?

**Comment by tobeornottobe81** [comment]
> @haslinghuis @ot0tot did we get this one sorted?

We do need 6 UARTs, so we are going to close this Pull Request #511

**Pull request closed without merging**
