### PR TITLE
add mambaf435_2023a

### PR DESCRIPTION
**Pull request by x4FF3**
Hi,

as i have talked to @freasy target for the MAMBAF435_2023A without timer for the motors. Please do not merge yet, could be i'll have to update and squash this PR in the next 2 to 3 days.

KR
David

### CODE REVIEW

**Comment by x4FF3** [comment]
removed cam control pin, because it is not accessible. also added timer for beeper.

**Comment by shaneshort** [comment]
@x4FF3 any news on this? I think it's important to try get this in before 4.5 goes final.

**Review by freasy — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]

**Comment by nerdCopter** [comment]
Marked 2 items resolved. note that Cam-Ctrl was removed.

**Review by haslinghuis — CHANGES_REQUESTED** [review]
Why are there no timers assigned to motors?

**Comment by freasy** [comment]
> Why are there no timers assigned to motors?

@haslinghuis because at32 has no pwm dshot code, thus will never use them and always run bitbange
 code

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]

**Comment by x4FF3** [comment]
current adc is working. answer to the question in pr #390

**Pull request merged**
