### PR TITLE
Disable Camera Control until feature is completed 

### PR DESCRIPTION
**Pull request by howels**
Disabling camera control until this is ready to allow for testing the flight performance of this target.

### CODE REVIEW

**Comment by haslinghuis** [comment]
@nerdCopter what is your take on this.

image

**Comment by nerdCopter** [comment]
* i'd prefer feature fixed in firmware than merging disabled defines.  but i understand the point of needing to move forward especially if a fix is not in progress.
* optionally forward some manually built .hex to select pilots for testing.
* when i first saw this PR, my instinct was not to approve, but i'm open to any necessities.

**Comment by nerdCopter** [comment]
i now see that `make config ; make NEUTRONRCF435` is broken on master.  i understand this PR more clearly.  is something in the works to repair source?

**Comment by haslinghuis** [comment]
Agree - also this board is not yet official afaik - as AT32 is finalizing development - developers can compile a hex locally.

FIx is here; https://github.com/betaflight/betaflight/pull/12767

**Comment by haslinghuis** [comment]
@howels merging now. Please revert when fixed.

**Review by haslinghuis — APPROVED** [review]

**Pull request merged**
