### PR TITLE
Add MICOAIR405MINI and MICOAIR743

### PR DESCRIPTION
**Pull request by haslinghuis**
Tested.

### CODE REVIEW

**Review by nerdCopter — APPROVED** [review]

**Comment by ot0tot** [comment]
Baro and gyro on the same SPI bus seems like a bad idea. You didn't notice any issues in testing?

**Comment by ot0tot** [comment]
Gyro interrupt pins not connected?

**Comment by haslinghuis** [comment]
Asked manufacturer about the missing exti pin. Did not notice issues.

`MICOAIR405MINI`

```bash
# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10       1       0    0.0%    0.0%         2      0     11       0
01 - (         SYSTEM)    966       4       1    0.3%    0.1%       671      0    979       2
02 - (           GYRO)   3205      25      20    8.0%    6.4%     26587      0   3263       0
03 - (         FILTER)   3205      35      26   11.2%    8.5%     35871      0   3263       0
04 - (            PID)   3205      70      62   22.4%   19.9%     82930      0   3263       0
05 - (            ACC)    792      26      19    2.0%    1.5%      6360      1    808      22
06 - (       ATTITUDE)    100      11       8    0.1%    0.0%       332      0    102      10
07 - (             RX)     10      22      16    0.0%    0.0%       205      0     33      21
08 - (         SERIAL)     99    6818       1   67.4%    0.0%      1117      0    100     152
09 - (       DISPATCH)    961       3       0    0.2%    0.0%       207      0    979       0
10 - (BATTERY_VOLTAGE)     50       2       1    0.0%    0.0%        32      0     51       2
11 - (BATTERY_CURRENT)     50       1       0    0.0%    0.0%        14      0     51       0
12 - ( BATTERY_ALERTS)      5       2       1    0.0%    0.0%         3      0      5       2
13 - (         BEEPER)     99       3       1    0.0%    0.0%        31      0    100       2
17 - (           BARO)     20      21       4    0.0%    0.0%       266      0    120       3
19 - (       ALTITUDE)     99       2       1    0.0%    0.0%        76      0    100       2
20 - (      DASHBOARD)     10       2       0    0.0%    0.0%         3      0     11       3
21 - (      TELEMETRY)    494       1       0    0.0%    0.0%       147      0    499       0
22 - (       LEDSTRIP)     60       0       0    0.0%    0.0%        16      0     61       0
23 - (    TRANSPONDER)    247       2       0    0.0%    0.0%        47      0    250       1
24 - (            OSD)     12      14       4    0.0%    0.0%       185      0    120       3
26 - (            CMS)     20       2       1    0.0%    0.0%        10      0     21       2
27 - (        VTXCTRL)      5       1       0    0.0%    0.0%         2      0      5       2
29 - (    ADCINTERNAL)      1       2       1    0.0%    0.0%         0      0      1       2
31 - (SPEED_NEGOTIATION)     99       8       1    0.0%    0.0%        49      0    100       7
32 - (       RC_STATS)     99       1       1    0.0%    0.0%        42      0    100       2
RX Check Function                   7       3                       259
Total (excluding SERIAL)                                36.4%
```

**Comment by haslinghuis** [comment]
- Boards are tested with Betaflight 4.5 and Ardupilot.
- EXTI pin is not exposed for BMI270
- Removed MAG from MICOAIR405 

image

**Comment by haslinghuis** [comment]
On MICOAIRf43 I2C2 used for onboard MAG and I2C1 is used for external usage.

image

**Comment by ot0tot** [comment]
> `MICOAIR405`
> 
> * supports BF, Ardupilot and INAV
> * Boards are tested with Betaflight 4.5 and Ardupilot.
> * EXTI pin is not exposed for BMI270
> * Removed MAG from MICOAIR405
> 

Baro and gyro are still both on the same SPI bus. Have you tested with GPS rescue or some other scenario where baro and gyro readings are important?

The BMI270 has interrupt pins:
image
image

**Comment by ot0tot** [comment]
> `MICOAIR405`
> 
> * supports BF, Ardupilot and INAV
> * Boards are tested with Betaflight 4.5 and Ardupilot.
> * EXTI pin is not exposed for BMI270
> * Removed MAG from MICOAIR405
> 
> image

What does M9 map to? There is no Motor 9 resource.

**Comment by haslinghuis** [comment]
image

Will ask.

**Comment by ot0tot** [comment]
Do you have these FCs in hand? Can you post the output of `status`?

**Comment by haslinghuis** [comment]
```
MCU F40X Clock=168MHz (PLLP-HSE), Vref=3.30V, Core temp=34degC
Stack size: 2048, Stack address: 0x1000fff0
Configuration: CONFIGURED, size: 4163, max available: 16384
Devices detected: SPI:2, I2C:0
Gyros detected: gyro 1 shared
GYRO=BMI270, ACC=BMI270, BARO=DPS310
OSD: MSP (53 x 20)
System Uptime: 9 seconds, Current Time: 2024-05-24T07:15:41.319+00:00
CPU:25%, cycle time: 312, GYRO rate: 3205, RX rate: 15, System rate: 9
Voltage: 0 * 0.01V (0S battery - INIT)
I2C Errors: 0
SD card: Manufacturer 0xfe, 3932160kB, 01/2024, v2.0, 'SD16G'
Filesystem: Ready
GPS: NOT ENABLED
Arming disable flags: RXLOSS ANGLE CLI MSP
```

```
MCU H743 (Rev.V) Clock=480MHz, Vref=3.30V, Core temp=36degC
Stack size: 2048, Stack address: 0x2001fff8
Configuration: CONFIGURED, size: 4258, max available: 131072
Devices detected: SPI:1, I2C:2
Gyros detected: gyro 1
GYRO=BMI270, ACC=BMI270, BARO=DPS310, MAG=IST8310
OSD: MSP (53 x 20)
System Uptime: 9 seconds, Current Time: 2024-05-24T07:14:48.517+00:00
CPU:11%, cycle time: 312, GYRO rate: 3205, RX rate: 15, System rate: 10
Voltage: 0 * 0.01V (0S battery - INIT)
I2C Errors: 0
SD card: Manufacturer 0x3, 3872256kB, 04/2015, v8.0, 'SS04G'
Filesystem: Ready
GPS: NOT ENABLED
Arming disable flags: RXLOSS ANGLE CLI MSP
```

**Review by blckmn — APPROVED** [review]

**Pull request merged**
