### PR TITLE
add BAYCK_DOLPHIN_MINI

### PR DESCRIPTION
**Pull request by BAYCKRC**
add BAYCK_DOLPHIN_MINI

### CODE REVIEW

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]
approving; visually scanned only

**Comment by nerdCopter** [comment]
@BAYCKRC , need unified-target for 4.4.x

**Comment by BAYCKRC** [comment]
I am using an AT32 chip. Is version 4.4 supported?



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 13, 2023 22:26 PM
To: ***@***.***&gt;;
Cc: "BAYCK ***@***.******@***.***&gt;;
Subject: Re: [betaflight/config] add BAYCK_DOLPHIN_MINI (PR #192)




 
@BAYCKRC , need unified-target for 4.4.x

**Comment by BAYCKRC** [comment]
Thank you for your concern! We, BAYCKRC, will closely contact your organization next week to determine hardware manufacturing and other matters!



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 13, 2023 22:35 PM
To: ***@***.***&gt;;
Cc: "BAYCK ***@***.******@***.***&gt;;
Subject: Re: [betaflight/config] add BAYCK_DOLPHIN_MINI (PR #192)




 
@BAYCKRC , my mistake, sorry no AT32 support in 4.4. sorry to disturb.

**Pull request merged**
