### PR TITLE
Support FLYWOOF722MINI

### PR DESCRIPTION
**Pull request by hayorov**
Support newboard/target FLYWOOF722MINI
https://flywoo.net/products/goku-f722-mini-v2-40a-bls-20x20-stack

From device:

```
2024-03-08 @11:32:44 -- Board: FLWO/FLYWOOF722MINI(STM32F7X2), version: 0

2024-03-08 @11:32:44 -- Unique device ID: 0x1a00423133510b36313534
```

For validation resources:
```
# resource
resource BEEPER 1 C14
resource MOTOR 1 B01
resource MOTOR 2 B04
resource MOTOR 3 B03
resource MOTOR 4 A15
resource MOTOR 5 C08
resource MOTOR 6 C09
resource MOTOR 7 B06
resource MOTOR 8 B07
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_TX 3 B10
resource SERIAL_TX 4 A00
resource SERIAL_TX 5 C12
resource SERIAL_TX 6 C06
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 A03
resource SERIAL_RX 3 B11
resource SERIAL_RX 4 A01
resource SERIAL_RX 5 D02
resource SERIAL_RX 6 C07
resource I2C_SCL 1 B08
resource I2C_SDA 1 B09
resource LED 1 C15
resource SPI_SCK 1 A05
resource SPI_SCK 2 B13
resource SPI_SCK 3 C10
resource SPI_MISO 1 A06
resource SPI_MISO 2 B14
resource SPI_MISO 3 C11
resource SPI_MOSI 1 A07
resource SPI_MOSI 2 B15
resource SPI_MOSI 3 B05
resource ADC_BATT 1 C01
resource ADC_RSSI 1 C02
resource ADC_CURR 1 C00
resource PINIO 1 B00
resource FLASH_CS 1 C13
resource OSD_CS 1 B12
resource GYRO_EXTI 1 C03
resource GYRO_EXTI 2 C04
resource GYRO_CS 1 A04
resource GYRO_CS 2 B02
```

resource show all

```
# resource show all
Currently active IO resource assignments:
(reboot to update)
--------------------
A00: FREE
A01: FREE
A02: SERIAL_TX 2
A03: SERIAL_RX 2
A04: GYRO_CS 1
A05: SPI_SCK 1
A06: SPI_MISO 1
A07: SPI_MOSI 1
A08: FREE
A09: FREE
A10: FREE
A11: USB
A12: USB
A13: SWD
A14: SWD
A15: MOTOR 4
B00: PINIO 1
B01: MOTOR 1
B02: PREINIT 2
B03: MOTOR 3
B04: MOTOR 2
B05: SPI_MOSI 3
B06: FREE
B07: FREE
B08: I2C_SCL 1
B09: I2C_SDA 1
B10: SERIAL_TX 3
B11: SERIAL_RX 3
B12: PREINIT 4
B13: SPI_SCK 2
B14: SPI_MISO 2
B15: SPI_MOSI 2
C00: ADC_CURR
C01: ADC_BATT
C02: FREE
C03: GYRO_EXTI
C04: FREE
C05: FREE
C06: FREE
C07: FREE
C08: FREE
C09: FREE
C10: SPI_SCK 3
C11: SPI_MISO 3
C12: FREE
C13: FLASH_CS
C14: BEEPER
C15: LED 1
D00: FREE
D01: FREE
D02: FREE
D03: FREE
D04: FREE
D05: FREE
D06: FREE
D07: FREE
D08: FREE
D09: FREE
D10: FREE
D11: FREE
D12: FREE
D13: FREE
D14: FREE
D15: FREE
E00: FREE
E01: FREE
E02: FREE
E03: FREE
E04: FREE
E05: FREE
E06: FREE
E07: FREE
E08: FREE
E09: FREE
E10: FREE
E11: FREE
E12: FREE
E13: FREE
E14: FREE
E15: FREE
F00: FREE
F01: FREE
F02: FREE
F03: FREE
F04: FREE
F05: FREE
F06: FREE
F07: FREE
F08: FREE
F09: FREE
F10: FREE
F11: FREE
F12: FREE
F13: FREE
F14: FREE
F15: FREE

Currently active Timers:
-----------------------
TIM1: FREE
TIM2: FREE
TIM3: FREE
TIM4: FREE
TIM5: FREE
TIM6: FREE
TIM7: FREE
TIM8:
    CH3 : DSHOT_BITBANG 2
    CH4 : DSHOT_BITBANG 1
TIM9: FREE
TIM10: FREE
TIM11: FREE
TIM12: FREE
TIM13: FREE
TIM14: FREE

Currently active DMA:
--------------------
DMA1 Stream 0: SPI_MISO 3
DMA1 Stream 1: FREE
DMA1 Stream 2: FREE
DMA1 Stream 3: FREE
DMA1 Stream 4: FREE
DMA1 Stream 5: SPI_MOSI 3
DMA1 Stream 6: FREE
DMA1 Stream 7: FREE
DMA2 Stream 0: ADC
DMA2 Stream 1: FREE
DMA2 Stream 2: SPI_MISO 1
DMA2 Stream 3: SPI_MOSI 1
DMA2 Stream 4: DSHOT_BITBANG 2
DMA2 Stream 5: FREE
DMA2 Stream 6: FREE
DMA2 Stream 7: DSHOT_BITBANG 1

```

### CODE REVIEW

**Comment by haslinghuis** [comment]
@hayorov did you check https://github.com/betaflight/config/blob/master/configs/FLYWOOF722PROV2/config.h

**Comment by hayorov** [comment]
@haslinghuis  Yes, I've seen this target, of course. I'm not 100% sure, but the hardware looks very similar for the Flywoo MINI and PRO V2 boards. Unfortunately, Flywoo flashes and ships them as FLYWOOF722PROV2 and FLYWOOF722MINI, respectively.

I understand that you might want to avoid similar targets in the repository, but is there any way to indicate that this is the same target/board as FLYWOOF722PROV2? Something like a board alias or board family?

Amyways, I'm confrotamble to maintain a new target FLYWOOF722MINI aonce I own the board :) What do you think?

**Comment by haslinghuis** [comment]
@hayorov Could be another board indeed. Let's wait until we have more info.

Have created these two targets with flywoo directly (only have the 30x30 one here): 

F722PRO(3030) is MPU6000/42688,   F722PRO MINI(2020) is 42688

**Comment by sugaarK** [comment]
speaking to flywoo there is no need for this PR
Screenshot 2024-03-27 at 7 01 16 pm

**Pull request closed without merging**
