### PR TITLE
Update SPEEDYBEEF405MINI (remove ESC telemetry)

### PR DESCRIPTION
**Pull request by ot0tot**
Remove ESC telemetry define because this stack ships with a BLHeli_S ESC, and Speedybee does not even make a 20x20 BLHeli32 ESC. 

https://www.speedybee.com/speedybee-f405-mini-bls-35a-20x20-stack/

### CODE REVIEW

**Comment by haslinghuis** [comment]
image

**Comment by ot0tot** [comment]
N = Not connected

**Comment by haslinghuis** [comment]
Makes sense to remove from stack configuration - but the FC exposes a specific UART if user would use another ESC

image

**Comment by ot0tot** [comment]
Understood, but lots of FCs have provisions for ESC telemetry and they are not included in the configs.

**Comment by haslinghuis** [comment]
Agree if unused we should not configure it. As long we can find the right port to use in documentation.

**Review by haslinghuis — APPROVED** [review]

**Comment by nerdCopter** [comment]
So essentially this just disable the ports-tab pre-configured state, correct?

**Pull request merged**
